### ISSUE TITLE
Possible to provide full code ?

### ISSUE THREAD

**Issue by stevexxs** [hypernote/stocknet#1]
Hi,

I am very interesting with your code about using Temporal Convolutional Networks to do the stock prediction. 
Is there any specific paper for this stock prediction project that I can refer?
Could you please help provide code for your great work ?
Thanks so much!

**Comment by hjc5858** [comment]
Hi,

very interesting code,can you provide your full code?

**Comment by hypernote** [comment]
Hello Guys, sorry for the late response. I'll now provide some partial code and scripts I have available now for StockNet.
